### ISSUE TITLE
Order of configure/detach

### ISSUE THREAD

**Issue by mcollina** [nearform/nscale-planner#1]
At the moment the planner does two completely separated phases of planning:
1. it plans the 'shutdown' of all the previous containers (detach cmd)
2. it plans the 'startup' of all the new containers (configure cmd)

This is due to a bug that @pelger pointed out in the preparation of a demo: he cannot start a new container because there were already another connected to the exposed port :warning:. So, what should we do?

I think that the right strategy is to configure an instance when detaching the other: e.g. if we have 10 AMI instances inside an ELB, and we need to spawn 10 new ones, we delete one and we spawn another. In this case, we have a 'rolling' deployment, and we might need some way to roll it back if something goes wrong.

I think we should use the name of the container definition to determine the containers on which we enable this incremental deployment. This is because an EC2 can contain containers of different types, and we can't generally remove a single one, we need to replace exactly the ones of the same type.

Moreover, we should reason with a deep-first logic, we update an AWS instance and then we move to the next one.

In any case, we need to improve this library to do the detach and configure phases at the same time.

@rjrodger @pelger please provide insights/guidance on this.

**Comment by pelger** [comment]
Hey Matteo,

The Main issue I see is one of performance, spinning up instances can take a lot of time particularly in a busy aws region. So I think we need to consider another approach. Firstly I would suggest that we look at docker container linking in more detail to see if it is possible to sidestep the port sharing issue altogether. Failing that it should be possible to more tightly manage port assignment for docker containers. Rather than hard coding may be able to make these more dynamic. It is a difficult problem however because it really depends on the service that is running inside the container. 

In the end it may be that in a majority of cases stop then start is acceptable given that we can perform some kind of drain down / lock out during the restart.

Lets update in this thread as we progress.

P.

**Comment by mcollina** [comment]
Please have a look at this blog post: http://tech.blog.box.com/2014/06/node-js-high-availability-at-box/.

we might solve the port
problem by having a haproxy/nginx on each machine. The only catch? Maybe we might need a 'requires' relationship to know haproxy requires all the others.

What do you think?

**Comment by mcollina** [comment]
After a talk with @pelger we decided to have two planner algorithms a 'fast' one #3 and a 'safe' one #4.

I'm thinking if there might be a way to automatically detect when to add one instead of the other.
Do you think if we can stick an attribute in the containerDefinition? I think it's a static decision: you might want some containers to act the safe plan, and others to act the fast plan.
